config/routes.rb
Rails.application.routes.draw do
  get 'linkedin/index'

  get 'opps/show'

  resources :opps
  resources :organisations
  devise_for :volunteers, :controllers => { registrations: 'registrations' }
  root 'application#index'
  get 'devise/sessions#destroy', to: 'application#index'

end

app/models/cause.rb
class Cause < ActiveRecord::Base
end

app/models/commitment.rb
class Commitment < ActiveRecord::Base
  belongs_to :volunteer
  belongs_to :organisation
end

app/models/opp.rb
class Opp < ActiveRecord::Base
  belongs_to :organisation
  has_many :opp_skills
  has_many :skills, through: :opp_skills
end

app/models/opp_skill.rb
class OppSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :opp
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :volunteers
  has_many :opps
end

app/models/organisation_volunteer.rb
class OrganisationVolunteer < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :opp_skills
  has_many :opps, through: :opp_skills
  has_many :volunteer_skills
  has_many :volunteers, through: :volunteer_skills
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base

  belongs_to :organisation
  has_many :volunteer_skills
  has_many :skills, through: :volunteer_skills
  has_many :commitments
  has_many :causes
  has_many :opps, through: :commitments


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email
end

app/models/volunteer_skill.rb
class VolunteerSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :volunteer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index 
    @organisations = Organisation.order(:name);
  end
end

app/controllers/linkedin_controller.rb
class LinkedinController < ApplicationController
  def index
  end
end

app/controllers/opps_controller.rb
class OppsController < ApplicationController
  before_action :set_opp, only: [:show, :edit, :update, :destroy]


  def index
    @opps = Opp.all
  end

  def show
  end

  def new
    @opp = Opp.new
  end

  # GET /posts/1/edit
  def edit
  end

  # PATCH/PUT /opps/1
  # PATCH/PUT /opps/1.json
  def update
    respond_to do |format|
      if @opp.update(opp_params)
        format.html { redirect_to @opp, notice: 'Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @opp }
      else
        format.html { render :edit }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opps/1
  # DELETE /opps/1.json
  def destroy
    @opp.destroy
    respond_to do |format|
      format.html { redirect_to opps_url, notice: 'Opportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @opp = Opp.new(opp_params)

    respond_to do |format|
      if @opp.save
        format.html { redirect_to @opp, notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @opp }
      else
        format.html { render :new }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_opp
      @opp = Opp.find(params[:id])
    end

    def opp_params
      params.require(:opp).permit(:name, :description)
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
before_action :find_organisation, only: [:show, :edit, :update, :destroy]
  def new 
    @organisation = Organisation.new 
  end 

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      redirect_to @organisation
    else 
      render :new
    end
  end

  def show 
  end 

  def edit
  end 

  def update
    if @organisation.update(organisation_params)
      redirect_to @organisation
    else 
      render :edit
    end 
  end 

  def destroy 
    @organisation.destroy()
    redirect_to root_path
  end
private 

def find_organisation
  @organisation = Organisation.find(params[:id])
end

def organisation_params
  params.require(:organisation).permit(
    :name, 
    :description,
    :image
    )
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:volunteer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:volunteer).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def index 
    @organisations = Organisation.order(:name);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linkedin_helper.rb
module LinkedinHelper
end

app/helpers/opps_helper.rb
module OppsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
<% if volunteer_signed_in? %>
  <h1>Hey there!</h1>
  <%= link_to "Sign out", destroy_volunteer_session_path, :method => :delete %>
  <%= link_to "New Organisation", new_organisation_path %> 
  <% @organisations.each do |organisation| %> 
    <p class="organisation"><%= link_to organisation.name, organisation%></p>
    <% end %>
                    <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Latest Opps</th>
                                <th>Commitment</th>
                                <th>Time Left</th>
                                <th>Committed Vollies</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1,001</td>
                                <td>Lorem</td>
                                <td>ipsum</td>
                                <td>dolor</td>
                                <td><img src="assets/images/image_u29.png" /></td>
                            </tr>
                            <tr>
                                <td>1,002</td>
                                <td>amet</td>
                                <td>consectetur</td>
                                <td>adipiscing</td>
                                <td><img src="assets/images/image_u29.png" /></td>
                            </tr>
                            <tr>
                                <td>1,003</td>
                                <td>Integer</td>
                                <td>nec</td>
                                <td>odio</td>
                                <td><img src="assets/images/image_u29.png" /></td>
                            </tr>
                            <tr>
                                <td>1,003</td>
                                <td>libero</td>
                                <td>Sed</td>
                                <td>cursus</td>
                                <td><img src="assets/images/image_u29.png" /></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<% else %>
  <h1>Communiteer</h1>
  <p>Sign up today!</p>
  <%= link_to "Sign In", new_volunteer_session_path %>
  <%= link_to "Sign Up", new_volunteer_registration_path %>
<% end %>
</body>
</html>

app/views/linkedin/index.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="images/logo-solo.png">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <!--<div class="page">
        <h1>Linkedin Integration</h1>

        <ul id="js-messages">
            <li>Messages from our code will appear here.</li>
        </ul>
    </div>-->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- The following displays a Linkedin Login button
         The callback in data-onAuth will be called when the user is logged in
         The callback in data-onLogout will be called when the user logs out
      -->
    <!--
         This loads the Linkedin JS API.
         The onLoad callback is called when the Linkedin JS API has been loaded.
    -->
    <script type="text/javascript" src="http://platform.linkedin.com/in.js">
        api_key: 75dzuxicwzqe4h
        onLoad:  onLinkedInLoad
        authorize: true
    </script>

    <!--<script type="text/javascript" src="linkedin.js"></script>-->
    <script type="text/javascript">

        // Setup an event listener to make an API call once auth is complete
        function onLinkedInLoad() {
        }

        // Handle the successful return from the API call
        function onSuccess(data) {
            window.location.replace("/opps");
        }

        // Handle an error response from the API call
        function onError(error) {
            alert(error);
        }

        // Use the API call wrapper to request the member's basic profile data
        function getProfileData() {
            IN.API.Raw("/people/~").result(onSuccess).error(onError);
        }

    </script>

</head>
<body>


    <div class="container-fluid">
        <div class="row">
            <div style="padding-left:600px;padding-top:200px;">
                <script type="IN/Login" data-onauth="getProfileData">
                </script>

            </div>
        </div>
    </div>

</body>
</html>

app/views/opps/_form.html.erb
<%= form_for(@opp) do |f| %>
  <% if @opp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opp.errors.count, "error") %> prohibited this Opportunity from being saved:</h2>

      <ul>
      <% @opp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Description' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opps/_opp.html.erb
 <style type="text/css">
.numbers {
    padding: 0px;
    width: 45px;
    text-align: center;
    font-family: Arial;
    font-size: 28px;
    font-weight: bold;    /* options are normal, bold, bolder, lighter */
    font-style: normal;   /* options are normal or italic */
    color: #FFFFFF;       /* change color using the hexadecimal color codes for HTML */
}
.title {    /* the styles below will affect the title under the numbers, i.e., “Days”, “Hours”, etc. */
    border-style: none;
    padding: 0px 0px 3px 0px;
    width: 45px;
    text-align: center;
    font-family: Arial;
    font-size: 10px;
    font-weight: bold;    /* options are normal, bold, bolder, lighter */
    color: #FFFFFF;       /* change color using the hexadecimal color codes for HTML */
}
#table {
    width: 400px;
    height: 70px;
    border-style: ridge;
    border-width: 3px;
    border-color: #666666;       /* change color using the hexadecimal color codes for HTML */
    background-color: #222222;   /* change color using the hexadecimal color codes for HTML */
    margin: 0px auto;
    position: relative;   /* leave as "relative" to keep timer centered on your page, or change to "absolute" then change the values of the "top" and "left" properties to position the timer */
    top: 0px;            /* change to position the timer */
    left: 0px;            /* change to position the timer; delete this property and it's value to keep timer centered on page */
}
</style>

<script type="text/javascript">

/*
Count down until any date script-
By JavaScript Kit (www.javascriptkit.com)
Over 200+ free scripts here!
Modified by Robert M. Kuhnhenn, D.O.
on 5/30/2006 to count down to a specific date AND time,
on 10/20/2007 to a new format, and 1/10/2010 to include
time zone offset.
*/
var year=2015;    //-->Enter the count down target date YEAR
var month=12;      //-->Enter the count down target date MONTH
var day=21;       //-->Enter the count down target date DAY
var hour=18;      //-->Enter the count down target date HOUR (24 hour clock)
var minute=38;    //-->Enter the count down target date MINUTE
var tz=-5;        //-->Offset for your timezone in hours from UTC (see http://wwp.greenwichmeantime.com/index.htm to find the timezone offset for your location)

//    DO NOT CHANGE THE CODE BELOW!
var montharray=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");

function countdown(yr,m,d,hr,min){
    theyear=yr;themonth=m;theday=d;thehour=hr;theminute=min;
    var today=new Date();
    var todayy=today.getYear();
    if (todayy < 1000) {todayy+=1900;}
    var todaym=today.getMonth();
    var todayd=today.getDate();
    var todayh=today.getHours();
    var todaymin=today.getMinutes();
    var todaysec=today.getSeconds();
    var todaystring1=montharray[todaym]+" "+todayd+", "+todayy+" "+todayh+":"+todaymin+":"+todaysec;
    var todaystring=Date.parse(todaystring1)+(tz*1000*60*60);
    var futurestring1=(montharray[m-1]+" "+d+", "+yr+" "+hr+":"+min);
    var futurestring=Date.parse(futurestring1)-(today.getTimezoneOffset()*(1000*60));
    var dd=futurestring-todaystring;
    var dday=Math.floor(dd/(60*60*1000*24)*1);
    var dhour=Math.floor((dd%(60*60*1000*24))/(60*60*1000)*1);
    var dmin=Math.floor(((dd%(60*60*1000*24))%(60*60*1000))/(60*1000)*1);
    var dsec=Math.floor((((dd%(60*60*1000*24))%(60*60*1000))%(60*1000))/1000*1);
    if(dday<=0&&dhour<=0&&dmin<=0&&dsec<=0){
        document.getElementById('count2').innerHTML=current;
        document.getElementById('count2').style.display="inline";
        document.getElementById('count2').style.width="390px";
        document.getElementById('dday').style.display="none";
        document.getElementById('dhour').style.display="none";
        document.getElementById('dmin').style.display="none";
        document.getElementById('dsec').style.display="none";
        document.getElementById('days').style.display="none";
        document.getElementById('hours').style.display="none";
        document.getElementById('minutes').style.display="none";
        document.getElementById('seconds').style.display="none";
        document.getElementById('spacer1').style.display="none";
        document.getElementById('spacer2').style.display="none";
        return;
    }
    else {
        document.getElementById('count2').style.display="none";
        document.getElementById('dday').innerHTML=dday;
        document.getElementById('dhour').innerHTML=dhour;
        document.getElementById('dmin').innerHTML=dmin;
        document.getElementById('dsec').innerHTML=dsec;
        setTimeout("countdown(theyear,themonth,theday,thehour,theminute)",1000);
    }
}
</script>


 <h2><img width="80" height="80" src="<%= opp.organisation.image %>"/>  <%= link_to_unless_current opp.name, opp %></h2>
 <body onload="countdown(year,month,day,hour,minute)">
<div id="time" style="width: auto; height: 100px; background-color: #666666; margin: 2px;">
  <div class="button" style="float:right; margin: 20px;">Get involved now!</div>
  <table id="table" border="0" style="float:left;">
    <tr>
        <td align="center" colspan="6"><div class="numbers" id="count2" style="padding: 5px 0 0 0; "></div></td>
    </tr>
    <tr id="spacer1" style="background: none;">
        <td align="center" ><div class="numbers" ></div></td>
        <td align="center" ><div class="numbers" id="dday"></div></td>
        <td align="center" ><div class="numbers" id="dhour"></div></td>
        <td align="center" ><div class="numbers" id="dmin"></div></td>
        <td align="center" ><div class="numbers" id="dsec"></div></td>
        <td align="center" ><div class="numbers" ></div></td>
    </tr>
    <tr id="spacer2">
        <td align="center" ><div class="title" ></div></td>
        <td align="center" ><div class="title" id="days">Days</div></td>
        <td align="center" ><div class="title" id="hours">Hours</div></td>
        <td align="center" ><div class="title" id="minutes">Minutes</div></td>
        <td align="center" ><div class="title" id="seconds">Seconds</div></td>
        <td align="center" ><div class="title" ></div></td>
    </tr>
</table>

</div>
<h2>Opportunity Description</h2>
 <%= simple_format opp.description %>

<h2>Skills required</h2>
<p><%= opp.skills.first.name %></p>

<div class="button">Get Involved Now!</div>

app/views/opps/edit.html.erb
<h1>Editing Opportunity</h1>

<%= render 'form' %>

<%= link_to 'Show', @opp %> |
<%= link_to 'Back', opps_path %>

app/views/opps/index.html.erb
<br/>
<table style="border:none">
  <tr>
    <td><img width="80" height="80" src ="http://www.clker.com/cliparts/5/6/3/a/1194984675331456830utente_singolo_architett_01.svg.hi.png" /></td>
    <td>
      <table style="border:none">
        <tr>
          <td>
            <h1>Welcome back <%= current_volunteer.first_name + " " + current_volunteer.last_name%></h1>
          </td>
        </tr>
        <tr>
          <td>
            Level 3-10 Kudos
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<table>
  <thead>
    <tr>
      <td>Latest Opportunities</td>
      <td>Commitment</td>
      <td>Time Left</td>
      <td width=50>Committed Vollies</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @opps.each do |opp| %>
      <tr>
        <td><%= link_to opp.name, opp %></td>
        <td><%= opp.work_required %></td>
        <td><%= distance_of_time_in_words Time.now, opp.due_by %></td>
        <td>3</td>
        <td><img width="80" height="80" src="<%= opp.organisation.image %>" /></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/opps/new.html.erb
<h1>New Opportunity</h1>

<%= render 'form' %>

<%= link_to 'Back', opps_path %>

app/views/opps/show.html.erb
 <p id="notice"><%= notice %></p>

<%= render partial: @opp %>

 <%= link_to 'Back', opps_path %>

app/views/organisations/_form.html.erb
<%= form_for @organisation do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-lg btn-default" %>
    </div>
    <% end %>

app/views/organisations/edit.html.erb
<body>
  <div class="container">
    <%= render 'form' %>
  </div>
</body>

app/views/organisations/new.html.erb
<body>
  <div class="container">
    <%= render 'form' %>
  </div>
</body>

app/views/organisations/show.html.erb
<h1><%= @organisation.name %></h1>

<p> 
  <%= @organisation.description %> 
  </p>

<p><%= link_to "Edit Organisation", edit_organisation_path %></p>
<p><%= link_to "Delete Organisation", @organisation, method: :delete, data: { confirm: "Are you sure?"} %></p>